/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import Test.SistemaBakaan;
import funcionales.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import usuarios.Cliente;

/**
 *
 * @author PC-PERSONAL
 */
public class CarritoCompraVista extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private usuarios.Cliente clienteActual;

    /**
     * Creates new form CarritoCompraVista
     */
    public CarritoCompraVista() {
        initComponents();
        iniciarTabla();
        SistemaBakaan sistema = SistemaBakaan.getInstance();
        if (sistema.getUsuarioActual() instanceof Cliente) {
            clienteActual = (Cliente) sistema.getUsuarioActual();
        }
    }
    
    private void iniciarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"Producto", "Cantidad", "Precio Unitario", "Subtotal"}, 0
        );
        jTable1.setModel(modeloTabla);
    }

    public void agregarProducto(Producto producto) {
        // Mostrar diálogo para seleccionar cantidad
        String cantidadStr = JOptionPane.showInputDialog(this, 
            "Ingrese la cantidad para " + producto.getNombre() + " (Disponible: " + producto.getCantidadDisponible() + "):");
        
        try {
            int cantidad = Integer.parseInt(cantidadStr);
            if (cantidad > 0 && cantidad <= producto.getCantidadDisponible()) {
                if (clienteActual != null) {
                    clienteActual.getCarrito().agregarProducto(producto, cantidad);
                    actualizarTabla();
                    JOptionPane.showMessageDialog(this, "Producto agregado al carrito!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Cantidad inválida", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void actualizarTabla() {
        if (clienteActual == null) return;
        
        modeloTabla.setRowCount(0);
        double total = 0;
        
        for (int i = 0; i < clienteActual.getCarrito().getProductos().size(); i++) {
            Producto p = clienteActual.getCarrito().getProductos().get(i);
            int cantidad = clienteActual.getCarrito().getCantidades().get(i);
            double subtotal = p.getPrecio() * cantidad;
            total += subtotal;
            
            modeloTabla.addRow(new Object[]{
                p.getNombre(),
                cantidad,
                "$" + p.getPrecio(),
                "$" + subtotal
            });
        }
        
        // Actualizar total
        modeloTabla.addRow(new Object[]{"TOTAL", "", "", "$" + total});
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 250, 224));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Total", null, "0"},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoCompraVista().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
