
package grafica;
import funcionales.Producto;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class CarritoCompraAñadir extends javax.swing.JFrame {



    static private Producto productoSeleccionado;
    private double valorTotal = 0;

    // Constructor que recibe el producto seleccionado desde el catálogo
    public CarritoCompraAñadir(Producto producto) {
        initComponents();
        this.productoSeleccionado = producto;
        inicializarDatosProducto();
        configurarEventos();
    }

    // Inicializa la información del producto en la interfaz
    private void inicializarDatosProducto() {
        LB_NombreProducto.setText(productoSeleccionado.getNombre());
        TA_DescripcionProducto.setText(productoSeleccionado.getDescripcion());
        LB_ValorTotal.setText("0");
        Slider_Cantidad.setMinimum(1);
        Slider_Cantidad.setMaximum(productoSeleccionado.getCantidadDisponible());
        Slider_Cantidad.setValue(1);
    }

    // Configura eventos para que el valor total cambie al mover el slider
    private void configurarEventos() {
        Slider_Cantidad.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int cantidad = Slider_Cantidad.getValue();
                valorTotal = cantidad * productoSeleccionado.getPrecio();
                LB_ValorTotal.setText(String.format("$ %.2f", valorTotal));
            }
        });

        BTN_Cancelar.addActionListener(e -> dispose());

        BTN_AgregarCarrito.addActionListener(e -> {
            int cantidad = Slider_Cantidad.getValue();
            if (cantidad > productoSeleccionado.getCantidadDisponible()) {
                JOptionPane.showMessageDialog(
                        CarritoCompraAñadir.this,
                        "No hay suficiente cantidad disponible.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            JOptionPane.showMessageDialog(
                    CarritoCompraAñadir.this,
                    "Producto añadido al carrito:\n" +
                    productoSeleccionado.getNombre() +
                    "\nCantidad: " + cantidad +
                    "\nTotal: $" + String.format("%.2f", valorTotal)
            );

            dispose();
        });
    }

    /**
     * Inicialización automática de los componentes (NetBeans GUI Builder).
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LB_TitleProducto = new javax.swing.JLabel();
        BTN_AgregarCarrito = new javax.swing.JToggleButton();
        Slider_Cantidad = new javax.swing.JSlider();
        LB_NombreProducto = new javax.swing.JLabel();
        LB_Cantidad = new javax.swing.JLabel();
        BTN_Cancelar = new javax.swing.JButton();
        LB_TituloValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_DescripcionProducto = new javax.swing.JTextArea();
        LB_ValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 235, 199));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Añadir al carrito");

        LB_TitleProducto.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        LB_TitleProducto.setForeground(new java.awt.Color(51, 51, 51));
        LB_TitleProducto.setText("Producto:");

        BTN_AgregarCarrito.setText("Agregar al carrito");

        LB_NombreProducto.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        LB_NombreProducto.setForeground(new java.awt.Color(51, 51, 51));
        LB_NombreProducto.setText("Nombre del producto");

        LB_Cantidad.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        LB_Cantidad.setForeground(new java.awt.Color(51, 51, 51));
        LB_Cantidad.setText("Cantidad");

        BTN_Cancelar.setText("Cancelar");

        LB_TituloValor.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        LB_TituloValor.setForeground(new java.awt.Color(51, 51, 51));
        LB_TituloValor.setText("Valor Total:");

        TA_DescripcionProducto.setEditable(false);
        TA_DescripcionProducto.setBackground(new java.awt.Color(249, 235, 199));
        TA_DescripcionProducto.setColumns(20);
        TA_DescripcionProducto.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        TA_DescripcionProducto.setForeground(new java.awt.Color(51, 51, 51));
        TA_DescripcionProducto.setRows(5);
        TA_DescripcionProducto.setText("Descripción del producto\n");
        TA_DescripcionProducto.setBorder(null);
        jScrollPane1.setViewportView(TA_DescripcionProducto);

        LB_ValorTotal.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        LB_ValorTotal.setForeground(new java.awt.Color(51, 51, 51));
        LB_ValorTotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LB_TituloValor)
                    .addComponent(BTN_Cancelar)
                    .addComponent(LB_TitleProducto)
                    .addComponent(LB_Cantidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTN_AgregarCarrito))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_NombreProducto)
                            .addComponent(Slider_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LB_ValorTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_TitleProducto)
                    .addComponent(LB_NombreProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_Cantidad)
                    .addComponent(Slider_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_TituloValor)
                    .addComponent(LB_ValorTotal))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_AgregarCarrito)
                    .addComponent(BTN_Cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoCompraAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoCompraAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoCompraAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoCompraAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    new CarritoCompraAñadir(productoSeleccionado).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTN_AgregarCarrito;
    private javax.swing.JButton BTN_Cancelar;
    private javax.swing.JLabel LB_Cantidad;
    private javax.swing.JLabel LB_NombreProducto;
    private javax.swing.JLabel LB_TitleProducto;
    private javax.swing.JLabel LB_TituloValor;
    private javax.swing.JLabel LB_ValorTotal;
    private javax.swing.JSlider Slider_Cantidad;
    private javax.swing.JTextArea TA_DescripcionProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
