package grafica;

import funcionales.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CatalagoProductosVista extends javax.swing.JFrame {

    private List<Producto> listaProductos;
    private CarritoCompraVista carritoVista;
    private DefaultTableModel modeloTabla;

    public CatalagoProductosVista() {
        initComponents();
        this.listaProductos = new java.util.ArrayList<>();
        

    }
        //Constructor usado cuando se llama desde el programa
    public CatalagoProductosVista(List<Producto> listaProductos, CarritoCompraVista carritoVista) {
        this.listaProductos = listaProductos;
        this.carritoVista = carritoVista;

        initComponents();
        iniciarTabla();
        cargarProductos();
    }

    private void iniciarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Categoría", "Precio", "Disponible"}, 0
        );
        tablaProductos.setModel(modeloTabla);
    }

    private void cargarProductos() {

        if (listaProductos == null) {
            return; // Evita error
        }

        modeloTabla.setRowCount(0);

        for (Producto p : listaProductos) {
            modeloTabla.addRow(new Object[]{
                p.getIdProducto(),
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getCantidadDisponible()
            });
        }
    }

     private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        int fila = tablaProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto primero");
            return;
        }

        int idSeleccionado = (int) modeloTabla.getValueAt(fila, 0);

        Producto productoSeleccionado = listaProductos.stream()
                .filter(p -> p.getIdProducto() == idSeleccionado)
                .findFirst()
                .orElse(null);

        if (productoSeleccionado != null) {
            carritoVista.agregarProducto(productoSeleccionado);
            JOptionPane.showMessageDialog(this, "Producto añadido al carrito.");
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAgregarCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setForeground(new java.awt.Color(249, 235, 199));

        tablaProductos.setBackground(new java.awt.Color(249, 235, 199));
        tablaProductos.setForeground(new java.awt.Color(185, 148, 112));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setSelectionBackground(new java.awt.Color(249, 235, 199));
        jScrollPane1.setViewportView(tablaProductos);

        btnAgregarCarrito.setBackground(new java.awt.Color(249, 235, 199));
        btnAgregarCarrito.setForeground(new java.awt.Color(185, 148, 112));
        btnAgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Carrito 2.png"))); // NOI18N
        btnAgregarCarrito.setText("Añadir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnAgregarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCarrito)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalagoProductosVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
