/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

/**
 *
 * @author Carol
 */
public class editarProducto extends javax.swing.JFrame {

    /**
     * Creates new form editarProducto
     */
    public editarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        LB_Titulo = new javax.swing.JLabel();
        LB_SeleccioneProducto = new javax.swing.JLabel();
        LB_NombreProducto = new javax.swing.JLabel();
        LB_PrecioProducto = new javax.swing.JLabel();
        LB_CtdDispobible = new javax.swing.JLabel();
        LB_DescProd = new javax.swing.JLabel();
        CBox_SeleccionProductos = new javax.swing.JComboBox<>();
        TFLD_PrecioProducto = new javax.swing.JTextField();
        TFLD_CantidadDisponible = new javax.swing.JTextField();
        TFLD_NombreProducto = new javax.swing.JTextField();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Eliminar = new javax.swing.JButton();
        BTN_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel2.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Nombre del producto: ");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("jMenu1");

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 250, 224));

        LB_Titulo.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        LB_Titulo.setForeground(new java.awt.Color(0, 51, 51));
        LB_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Titulo.setText("Editar producto- Bakaan ");

        LB_SeleccioneProducto.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        LB_SeleccioneProducto.setForeground(new java.awt.Color(0, 51, 51));
        LB_SeleccioneProducto.setText("Seleccione el producto: ");
        LB_SeleccioneProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LB_NombreProducto.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        LB_NombreProducto.setForeground(new java.awt.Color(0, 51, 51));
        LB_NombreProducto.setText("Nombre del producto: ");
        LB_NombreProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LB_PrecioProducto.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        LB_PrecioProducto.setForeground(new java.awt.Color(0, 51, 51));
        LB_PrecioProducto.setText("Precio del producto: ");
        LB_PrecioProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LB_CtdDispobible.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        LB_CtdDispobible.setForeground(new java.awt.Color(0, 51, 51));
        LB_CtdDispobible.setText("Cantidad disponible: ");
        LB_CtdDispobible.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LB_DescProd.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        LB_DescProd.setForeground(new java.awt.Color(0, 51, 51));
        LB_DescProd.setText("Descripcion del producto:");
        LB_DescProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CBox_SeleccionProductos.setBackground(new java.awt.Color(255, 255, 255));
        CBox_SeleccionProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TFLD_PrecioProducto.setBackground(new java.awt.Color(255, 255, 255));
        TFLD_PrecioProducto.setForeground(new java.awt.Color(0, 0, 0));

        TFLD_CantidadDisponible.setBackground(new java.awt.Color(255, 255, 255));
        TFLD_CantidadDisponible.setForeground(new java.awt.Color(0, 0, 0));

        TFLD_NombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        TFLD_NombreProducto.setForeground(new java.awt.Color(0, 0, 0));

        BTN_Guardar.setBackground(new java.awt.Color(169, 179, 136));
        BTN_Guardar.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        BTN_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Guardar.setText("Guardar");
        BTN_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GuardarActionPerformed(evt);
            }
        });

        BTN_Eliminar.setBackground(new java.awt.Color(185, 148, 112));
        BTN_Eliminar.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        BTN_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Eliminar.setText("Eliminar");
        BTN_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EliminarActionPerformed(evt);
            }
        });

        BTN_Volver.setBackground(new java.awt.Color(120, 61, 25));
        BTN_Volver.setFont(new java.awt.Font("HP Simplified Jpan", 0, 14)); // NOI18N
        BTN_Volver.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Volver.setText("Volver");
        BTN_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VolverActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_NombreProducto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LB_SeleccioneProducto)
                                        .addComponent(LB_PrecioProducto))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LB_CtdDispobible)
                                        .addGap(17, 17, 17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBox_SeleccionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTN_Guardar)
                                    .addComponent(LB_DescProd))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(BTN_Eliminar)
                                        .addGap(39, 39, 39)
                                        .addComponent(BTN_Volver))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFLD_CantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFLD_PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFLD_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LB_Titulo)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_SeleccioneProducto)
                            .addComponent(CBox_SeleccionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_NombreProducto)
                            .addComponent(TFLD_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_PrecioProducto)
                            .addComponent(TFLD_PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LB_CtdDispobible))
                    .addComponent(TFLD_CantidadDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LB_DescProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_Guardar)
                            .addComponent(BTN_Eliminar)
                            .addComponent(BTN_Volver))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EliminarActionPerformed

    private void BTN_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Eliminar;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Volver;
    private javax.swing.JComboBox<String> CBox_SeleccionProductos;
    private javax.swing.JLabel LB_CtdDispobible;
    private javax.swing.JLabel LB_DescProd;
    private javax.swing.JLabel LB_NombreProducto;
    private javax.swing.JLabel LB_PrecioProducto;
    private javax.swing.JLabel LB_SeleccioneProducto;
    private javax.swing.JLabel LB_Titulo;
    private javax.swing.JTextField TFLD_CantidadDisponible;
    private javax.swing.JTextField TFLD_NombreProducto;
    private javax.swing.JTextField TFLD_PrecioProducto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
