/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import test.SistemaBakaan;
import javax.swing.JOptionPane;

/**
 *
 * @author ValentinaVeraLozano
 */
public class inicioRegistro extends javax.swing.JFrame {

    /**
     * Creates new form inicioRegistro
     */
    public inicioRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        Pane_IniciarSesion = new javax.swing.JPanel();
        LB_InicioSesion = new javax.swing.JLabel();
        Field_Correo = new javax.swing.JTextField();
        PwdField_Contrasena = new javax.swing.JPasswordField();
        LB_Correo = new javax.swing.JLabel();
        LB_Contrasena = new javax.swing.JLabel();
        BTN_IniciarSesion = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pane_IniciarSesion.setBackground(new java.awt.Color(254, 250, 224));

        LB_InicioSesion.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        LB_InicioSesion.setForeground(new java.awt.Color(51, 51, 51));
        LB_InicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_InicioSesion.setText("Iniciar Sesión");

        Field_Correo.setText("Ingresa tu correo");

        PwdField_Contrasena.setText("Contraseña");

        LB_Correo.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        LB_Correo.setForeground(new java.awt.Color(51, 51, 51));
        LB_Correo.setText("Correo:");

        LB_Contrasena.setBackground(new java.awt.Color(51, 51, 51));
        LB_Contrasena.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        LB_Contrasena.setForeground(new java.awt.Color(51, 51, 51));
        LB_Contrasena.setText("Contraseña:");

        BTN_IniciarSesion.setBackground(new java.awt.Color(120, 61, 25));
        BTN_IniciarSesion.setText("Iniciar Sesión");
        BTN_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_IniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pane_IniciarSesionLayout = new javax.swing.GroupLayout(Pane_IniciarSesion);
        Pane_IniciarSesion.setLayout(Pane_IniciarSesionLayout);
        Pane_IniciarSesionLayout.setHorizontalGroup(
            Pane_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pane_IniciarSesionLayout.createSequentialGroup()
                .addGroup(Pane_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pane_IniciarSesionLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(BTN_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pane_IniciarSesionLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(Pane_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LB_Contrasena)
                            .addComponent(LB_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PwdField_Contrasena)
                            .addComponent(Field_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pane_IniciarSesionLayout.createSequentialGroup()
                .addGap(0, 87, Short.MAX_VALUE)
                .addComponent(LB_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        Pane_IniciarSesionLayout.setVerticalGroup(
            Pane_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pane_IniciarSesionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LB_InicioSesion)
                .addGap(18, 18, 18)
                .addComponent(LB_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(PwdField_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_IniciarSesionActionPerformed
        String correo = Field_Correo.getText();
        String contraseña = new String(PwdField_Contrasena.getPassword());

        SistemaBakaan sistema = SistemaBakaan.getInstance();

        if (sistema.iniciarSesion(correo, contraseña)) {
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso!");
            sistema.mostrarInterfazSegunTipoUsuario();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_IniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_IniciarSesion;
    private javax.swing.JTextField Field_Correo;
    private javax.swing.JLabel LB_Contrasena;
    private javax.swing.JLabel LB_Correo;
    private javax.swing.JLabel LB_InicioSesion;
    private javax.swing.JPanel Pane_IniciarSesion;
    private javax.swing.JPasswordField PwdField_Contrasena;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
